import { stringify } from "yaml";

export type Provider = "openai" | "anthropic" | "gemini";
export type DeployMode = "simple" | "full";
export type SafetyPreset = "dev" | "balanced" | "strict";

export interface ScaffoldOptions {
  projectName: string;
  providers: Provider[];
  mode: DeployMode;
  safetyPreset: SafetyPreset;
}

const CHEAP_PRIMARY: Record<Provider, string> = {
  openai: "openai/gpt-4o-mini",
  anthropic: "anthropic/claude-haiku",
  gemini: "gemini/gemini-flash",
};
const STANDARD_PRIMARY: Record<Provider, string> = {
  anthropic: "anthropic/claude-sonnet",
  openai: "openai/gpt-4o",
  gemini: "gemini/gemini-pro",
};

function pick<T>(providers: Provider[], table: Record<Provider, T>): T {
  const p = providers[0]!;
  return table[p];
}

/** Build a valid ai-guard.yaml (snake_case) from wizard answers. */
export function renderAiGuardYaml(opts: ScaffoldOptions): string {
  const cheapPrimary = pick(opts.providers, CHEAP_PRIMARY);
  // Prefer a provider that actually has a "standard" entry; else reuse first.
  const standardProvider =
    opts.providers.find((p) => p in STANDARD_PRIMARY) ?? opts.providers[0]!;
  const standardPrimary = STANDARD_PRIMARY[standardProvider];

  // Optional fallback: a different provider's cheap model, when available.
  const altProvider = opts.providers.find((p) => p !== opts.providers[0]);

  const config: Record<string, unknown> = {
    project: { name: opts.projectName, environment: "development" },
    providers: Object.fromEntries(
      opts.providers.map((p) => [
        p,
        { api_key: `env/${p.toUpperCase()}_API_KEY` },
      ]),
    ),
    budgets: {
      global: {
        monthly_usd: 500,
        alert_at_percent: 80,
        hard_stop_at_percent: 100,
      },
      by_user_type: {
        anonymous: { daily_usd: 0.02, daily_requests: 5, models: ["cheap"] },
        logged_in: {
          daily_usd: 0.25,
          daily_requests: 50,
          models: ["cheap", "standard"],
        },
      },
    },
    features: {
      support_chat: {
        safety: opts.safetyPreset,
        model_class: "cheap",
        max_tokens: 500,
      },
    },
    routing: { degrade_at_percent: 80 },
    model_classes: {
      cheap: {
        primary: cheapPrimary,
        ...(altProvider ? { fallback: CHEAP_PRIMARY[altProvider] } : {}),
      },
      standard: { primary: standardPrimary },
    },
    safety: {
      preset: opts.safetyPreset,
      injection_model: cheapPrimary,
    },
    observability: { provider: opts.mode === "full" ? "langfuse" : "none" },
  };

  const header =
    "# Generated by create-ai-guard. Edit freely.\n" +
    "# Provider api_key env/VAR refs are resolved by the Ai-Guard API at load time.\n\n";
  return header + stringify(config);
}

/** Build a .env with placeholders for the chosen providers + service URLs. */
export function renderEnv(opts: ScaffoldOptions): string {
  const lines: string[] = [
    "# Provider keys (consumed by the LiteLLM proxy)",
    ...opts.providers.map((p) => `${p.toUpperCase()}_API_KEY=`),
    "",
    "# LiteLLM proxy",
    "LITELLM_MASTER_KEY=sk-ai-guard-local",
    "",
    "# Ai-Guard API",
    "PORT=3000",
    "AI_GUARD_API_KEY=sk-ai-guard-api-local",
    "DATABASE_URL=postgres://postgres:postgres@localhost:5432/aiguard",
    "LITELLM_BASE_URL=http://localhost:4000",
    "AI_GUARD_CONFIG=ai-guard.yaml",
  ];
  if (opts.safetyPreset !== "dev") {
    lines.push(
      "",
      "# Safety (Presidio)",
      "PRESIDIO_ANALYZER_URL=http://localhost:5002",
      "PRESIDIO_ANONYMIZER_URL=http://localhost:5001",
    );
  }
  return lines.join("\n") + "\n";
}

/** The compose file the user should run for the chosen mode. */
export function composeFileFor(mode: DeployMode): string {
  return mode === "full"
    ? "-f docker-compose.simple.yml -f docker-compose.full.yml"
    : "-f docker-compose.simple.yml";
}
